---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: kubespray-docker
    box: coreos-stable
    # yamllint disable-line
    box_url: "https://stable.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../
  playbooks:
    converge: ../default/playbook.yml
    prepare: ../default/prepare.yml
  inventory:
    host_vars:
      kubespray-docker:
        ansible_python_interpreter: /opt/bin/python
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  directory: ../default/tests/
  lint:
    name: flake8
